services:
  - type: web
    name: fake-news-detection-api
    env: docker
    rootDir: backend
    autoDeploy: true
    envVars:
      - key: CORS_ORIGINS
        value: http://localhost:3000,http://127.0.0.1:3000
